const { neon } = require('@neondatabase/serverless');
const FIXED=[
 {key:'kampklar-daily',days:[1,2,3,4,5,6,0],time:'',title:'Tjek Kampklar for nye kampe, der skal tages stilling til'},
 {key:'aula-daily',days:[1,2,3,4,5,6,0],time:'',title:'Tjek Aula'},
 {key:'kampklar-mon',days:[1],time:'',title:'Meld Louie og Charlie til/fra tirsdagens fodbold i Kampklar'},
 {key:'football-tue',days:[2],time:'17:00',title:'Fodbold · Louie, Charlie og Sylvester'},
 {key:'kampklar-wed',days:[3],time:'',title:'Meld Louie og Charlie til/fra torsdagens fodbold i Kampklar'},
 {key:'football-thu',days:[4],time:'17:00',title:'Fodbold · Louie og Charlie'}
];
async function db(){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL mangler');const sql=neon(process.env.DATABASE_URL);await sql`CREATE TABLE IF NOT EXISTS weekplan_items (id bigserial PRIMARY KEY, item_date date NOT NULL, item_time text NOT NULL DEFAULT '', title text NOT NULL, kind text NOT NULL DEFAULT 'egen', recurring boolean NOT NULL DEFAULT false, removed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS weekplan_exclusions (rule_key text NOT NULL, item_date date NOT NULL, PRIMARY KEY(rule_key,item_date))`;return sql}
function datesBetween(a,b){const out=[],d=new Date(a+'T12:00:00Z'),e=new Date(b+'T12:00:00Z');while(d<=e){out.push(new Date(d));d.setUTCDate(d.getUTCDate()+1)}return out}
function iso(d){return d.toISOString().slice(0,10)}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,DELETE,OPTIONS');if(req.method==='OPTIONS')return res.status(204).end();try{const sql=await db();if(req.method==='GET'){const start=String(req.query.start||''),end=String(req.query.end||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))return res.status(400).json({error:'start og end kræves'});const rows=await sql`SELECT id::text,item_date::text AS date,item_time AS time,title,kind,recurring FROM weekplan_items WHERE item_date BETWEEN ${start}::date AND ${end}::date AND removed=false`;const exclusions=await sql`SELECT rule_key,item_date::text AS date FROM weekplan_exclusions WHERE item_date BETWEEN ${start}::date AND ${end}::date`;const ex=new Set(exclusions.map(x=>x.rule_key+'|'+x.date));for(const d of datesBetween(start,end)){for(const r of FIXED){const ds=iso(d);if(r.days.includes(d.getUTCDay())&&!ex.has(r.key+'|'+ds))rows.push({id:'fixed:'+r.key+':'+ds,date:ds,time:r.time,title:r.title,kind:'fast',recurring:true})}}rows.sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)||a.title.localeCompare(b.title));return res.status(200).json(rows)}if(req.method==='POST'){const x=req.body||{};if(!x.date||!x.title)return res.status(400).json({error:'date og title kræves'});const rows=await sql`INSERT INTO weekplan_items(item_date,item_time,title,kind,recurring) VALUES(${x.date}::date,${x.time||''},${x.title},${x.kind||'egen'},${!!x.recurring}) RETURNING id::text,item_date::text AS date,item_time AS time,title,kind,recurring`;return res.status(200).json(rows[0])}if(req.method==='DELETE'){const raw=String(req.query.id||'');if(raw.startsWith('fixed:')){const parts=raw.split(':'),rule=parts[1],date=parts[2];if(!FIXED.some(x=>x.key===rule)||!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({error:'ugyldig fast opgave'});await sql`INSERT INTO weekplan_exclusions(rule_key,item_date) VALUES(${rule},${date}::date) ON CONFLICT DO NOTHING`;return res.status(200).json({ok:true})}const id=Number(raw);if(!id)return res.status(400).json({error:'id kræves'});await sql`UPDATE weekplan_items SET removed=true,updated_at=now() WHERE id=${id}`;return res.status(200).json({ok:true})}res.status(405).json({error:'Method not allowed'})}catch(e){console.error(e);res.status(500).json({error:e.message})}};